# Generated by Django 4.2.4 on 2024-05-10 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.AddField(
            model_name='users',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 17, 0, 0)),
        ),
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='end_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='impact',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='insight',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='users',
            name='intensity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='likelihood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='pestle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 0, 0)),
        ),
        migrations.AddField(
            model_name='users',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='relevance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='sector',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='start_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='users',
            name='topic',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
