# Generated by Django 4.2.4 on 2024-05-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_email_remove_users_password_users_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='impact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
