# Generated by Django 4.2.4 on 2024-05-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_added_alter_users_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
