# Generated by Django 4.2.4 on 2024-05-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='intensity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='relevance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
