# Generated by Django 4.2.4 on 2024-05-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_intensity_alter_users_relevance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='likelihood',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
